config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/seissol/seissol:
      branch: master
      repo: https://github.com/seissol/seissol
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/seissol/seissol git:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-chartreuse-harrier.sh
        container: qc.acc_sleepy-scarlet-molly
  QC.Doc:
    repos:
      github.com/seissol/seissol find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-celadon-binturong.sh
        container: qc.doc_homey-peach-oyster
      github.com/seissol/seissol git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-chocolate-ragdoll.sh
        container: qc.doc_gamy-indigo-clam
      github.com/seissol/seissol markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-olive-birman.sh
        container: qc.doc_chummy-fuchsia-hornet
      github.com/seissol/seissol restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-carmine-meerkat.sh
        container: qc.doc_surly-linen-squirt
  QC.Lic:
    repos:
      github.com/seissol/seissol licensee:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-ultramarine-kiwi.sh
        container: qc.lic_wheezy-asparagus-gibbon
  QC.Met:
    repos:
      github.com/seissol/seissol cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-heliotrope-koala.sh
        container: qc.met_droopy-periwinkle-frise
  QC.Sec:
    repos:
      github.com/seissol/seissol bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-green-spider.sh
        container: qc.sec_paltry-cornflower-snake
  QC.Sty:
    repos:
      github.com/seissol/seissol flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-sepia-spaniel.sh
        container: qc.sty_slimy-heliotrope-beaver
      github.com/seissol/seissol hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-denim-lobster.sh
        container: qc.sty_tasty-crimson-spitz
      github.com/seissol/seissol jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-charcoal-pinscher.sh
        container: qc.sty_hasty-indigo-flounder
      github.com/seissol/seissol oclint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-cream-wombat.sh
        container: qc.sty_wimpy-viridian-coyote
  QC.Uni:
    repos:
      github.com/seissol/seissol pytest:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-linen-snail.sh
        container: qc.uni_whiny-lime-gecko
  QC.Ver:
    repos:
      github.com/seissol/seissol get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-bronze-havanese.sh
        container: qc.ver_trippy-platinum-warthog
timeout: 5400
