config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/seissol/seissol:
      branch: master
      repo: https://github.com/seissol/seissol
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/seissol/seissol git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-puce-mandrill.sh
        container: qc.acc_clammy-scarlet-buffalo
  QC.Doc:
    repos:
      github.com/seissol/seissol find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-pink-hound.sh
        container: qc.doc_hilly-lavender-cheetah
      github.com/seissol/seissol git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-silver-reindeer.sh
        container: qc.doc_leaky-taupe-bordeaux
      github.com/seissol/seissol markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-plum-reindeer.sh
        container: qc.doc_cozy-sangria-manatee
      github.com/seissol/seissol restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-linen-balinese.sh
        container: qc.doc_nerdy-purple-fossa
  QC.Lic:
    repos:
      github.com/seissol/seissol licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-eggplant-cheetah.sh
        container: qc.lic_leaky-saffron-kakapo
  QC.Met:
    repos:
      github.com/seissol/seissol cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-eggplant-olm.sh
        container: qc.met_pasty-viridian-owl
  QC.Sec:
    repos:
      github.com/seissol/seissol bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-white-mandrill.sh
        container: qc.sec_tacky-alizarin-wallaby
  QC.Sty:
    repos:
      github.com/seissol/seissol flake8:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-lavender-whale.sh
        container: qc.sty_hazy-orchid-fowl
      github.com/seissol/seissol hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-salmon-manatee.sh
        container: qc.sty_zippy-rose-kingfisher
      github.com/seissol/seissol jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-ivory-cow.sh
        container: qc.sty_greasy-dandelion-slug
      github.com/seissol/seissol oclint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-lavender-booby.sh
        container: qc.sty_smelly-ecru-ragdoll
  QC.Uni:
    repos:
      github.com/seissol/seissol pytest:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-carmine-cow.sh
        container: qc.uni_wheezy-cobalt-tuatara
  QC.Ver:
    repos:
      github.com/seissol/seissol get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-salmon-bird.sh
        container: qc.ver_snoopy-taupe-dodo
timeout: 5400
