config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/seissol/seissol:
      branch: master
      repo: https://github.com/seissol/seissol
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/seissol/seissol git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-linen-anteater.sh
        container: qc.acc_squirrely-pear-giraffe
  QC.Doc:
    repos:
      github.com/seissol/seissol find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-turquoise-newfoundland.sh
        container: qc.doc_woolly-aquamarine-mouse
      github.com/seissol/seissol git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-ruby-angelfish.sh
        container: qc.doc_pasty-lavender-squirt
      github.com/seissol/seissol markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-lemon-spaniel.sh
        container: qc.doc_wheezy-sapphire-retriever
      github.com/seissol/seissol restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-celadon-gharial.sh
        container: qc.doc_scummy-copper-owl
  QC.Lic:
    repos:
      github.com/seissol/seissol licensee:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-cornflower-iguana.sh
        container: qc.lic_snippy-mustard-harrier
  QC.Met:
    repos:
      github.com/seissol/seissol cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-orange-hamster.sh
        container: qc.met_scaly-wheat-salamander
  QC.Sec:
    repos:
      github.com/seissol/seissol bandit:
        commands:
        - /usr/bin/env sh .sqa/script.homely-zucchini-barb.sh
        container: qc.sec_tacky-corn-gopher
  QC.Sty:
    repos:
      github.com/seissol/seissol flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-violet-forest.sh
        container: qc.sty_squirrely-champagne-impala
      github.com/seissol/seissol hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-cinnamon-dog.sh
        container: qc.sty_boozy-cobalt-paradise
      github.com/seissol/seissol jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-maroon-catfish.sh
        container: qc.sty_droopy-scarlet-skunk
      github.com/seissol/seissol oclint:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-dandelion-giraffe.sh
        container: qc.sty_breezy-thistle-foxhound
  QC.Uni:
    repos:
      github.com/seissol/seissol pytest:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-xanthic-discus.sh
        container: qc.uni_crabby-turquoise-otter
  QC.Ver:
    repos:
      github.com/seissol/seissol get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-blue-moth.sh
        container: qc.ver_squeaky-lavender-gar
timeout: 5400
