config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/seissol/seissol:
      branch: sqaaas
      repo: https://github.com/seissol/seissol
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/seissol/seissol git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-cardinal-coral.sh
        container: qc.acc_whiny-sapphire-rottweiler
  QC.Doc:
    repos:
      github.com/seissol/seissol find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-dandelion-sloth.sh
        container: qc.doc_sickly-sangria-dalmatian
      github.com/seissol/seissol git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-alizarin-wolfhound.sh
        container: qc.doc_snippy-lime-seal
      github.com/seissol/seissol markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-auburn-eel.sh
        container: qc.doc_bluesy-amethyst-lemur
      github.com/seissol/seissol restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-aquamarine-booby.sh
        container: qc.doc_slimy-blue-baboon
  QC.Lic:
    repos:
      github.com/seissol/seissol licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-sangria-panda.sh
        container: qc.lic_cozy-vermilion-oriole
  QC.Met:
    repos:
      github.com/seissol/seissol cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-tomato-bonobo.sh
        container: qc.met_foggy-purple-hound
  QC.Sec:
    repos:
      github.com/seissol/seissol bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-xanthic-ray.sh
        container: qc.sec_tacky-red-crab
  QC.Sty:
    repos:
      github.com/seissol/seissol flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-white-spider.sh
        container: qc.sty_sloppy-platinum-gibbon
      github.com/seissol/seissol jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-pink-owl.sh
        container: qc.sty_sleepy-sangria-scorpion
  QC.Ver:
    repos:
      github.com/seissol/seissol get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-goldenrod-hamster.sh
        container: qc.ver_freaky-chocolate-deer
timeout: 5400
