config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/SeisSol/SeisSol:
      branch: master
      repo: https://github.com/SeisSol/SeisSol
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/SeisSol/SeisSol git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-charcoal-mule.sh
        container: qc.acc_chewy-teal-collie
  QC.Doc:
    repos:
      github.com/SeisSol/SeisSol find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-cyan-neanderthal.sh
        container: qc.doc_snappy-periwinkle-macaw
      github.com/SeisSol/SeisSol git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-brown-woodlouse.sh
        container: qc.doc_thirsty-purple-warthog
      github.com/SeisSol/SeisSol markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-lavender-maltese.sh
        container: qc.doc_baggy-cerulean-wolverine
      github.com/SeisSol/SeisSol restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-taupe-coati.sh
        container: qc.doc_grumpy-orchid-robin
  QC.Lic:
    repos:
      github.com/SeisSol/SeisSol licensee:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-lavender-flamingo.sh
        container: qc.lic_flimsy-burgundy-terrier
  QC.Met:
    repos:
      github.com/SeisSol/SeisSol cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-khaki-fish.sh
        container: qc.met_muzzy-ruby-bordeaux
  QC.Sec:
    repos:
      github.com/SeisSol/SeisSol bandit:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-cardinal-zorse.sh
        container: qc.sec_randy-cardinal-hyrax
  QC.Sty:
    repos:
      github.com/SeisSol/SeisSol flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-chartreuse-lemur.sh
        container: qc.sty_snazzy-firebrick-wombat
      github.com/SeisSol/SeisSol hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-purple-dollar.sh
        container: qc.sty_slimy-fuchsia-maltese
      github.com/SeisSol/SeisSol jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-maroon-sheep.sh
        container: qc.sty_squirrely-malachite-shrimp
      github.com/SeisSol/SeisSol oclint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-seashell-gopher.sh
        container: qc.sty_seedy-cinnabar-collie
  QC.Uni:
    repos:
      github.com/SeisSol/SeisSol pytest:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-aqua-caiman.sh
        container: qc.uni_wimpy-orange-koala
  QC.Ver:
    repos:
      github.com/SeisSol/SeisSol get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-copper-salamander.sh
        container: qc.ver_queasy-saffron-wolfhound
timeout: 5400
