config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/SeisSol/SeisSol:
      branch: master
      repo: https://github.com/SeisSol/SeisSol
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/SeisSol/SeisSol git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-olive-bonobo.sh
        container: qc.acc_skinny-gamboge-bracke
  QC.Doc:
    repos:
      github.com/SeisSol/SeisSol find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-auburn-newfoundland.sh
        container: qc.doc_squirrely-tan-tapir
      github.com/SeisSol/SeisSol git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-magnolia-stingray.sh
        container: qc.doc_breezy-magenta-starfish
      github.com/SeisSol/SeisSol markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-ochre-stoat.sh
        container: qc.doc_lanky-thistle-cichlid
      github.com/SeisSol/SeisSol restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-thistle-hyena.sh
        container: qc.doc_lousy-mustard-crane
  QC.Lic:
    repos:
      github.com/SeisSol/SeisSol licensee:
        commands:
        - /usr/bin/env sh .sqa/script.silly-silver-seal.sh
        container: qc.lic_baggy-taupe-coral
  QC.Met:
    repos:
      github.com/SeisSol/SeisSol cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-mustard-cichlid.sh
        container: qc.met_wheezy-platinum-javanese
  QC.Sec:
    repos:
      github.com/SeisSol/SeisSol bandit:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-wheat-newfoundland.sh
        container: qc.sec_cloudy-saffron-bison
  QC.Sty:
    repos:
      github.com/SeisSol/SeisSol flake8:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-rust-jackal.sh
        container: qc.sty_cheeky-olivine-antelope
      github.com/SeisSol/SeisSol jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-dandelion-giraffe.sh
        container: qc.sty_sleepy-firebrick-orangutan
  QC.Ver:
    repos:
      github.com/SeisSol/SeisSol get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-ecru-jellyfish.sh
        container: qc.ver_jumpy-asparagus-pig
timeout: 5400
