config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/seissol/seissol:
      branch: master
      repo: https://github.com/seissol/seissol
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/seissol/seissol git:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-crimson-burmese.sh
        container: qc.acc_craggy-violet-dachshund
  QC.Doc:
    repos:
      github.com/seissol/seissol find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-white-millipede.sh
        container: qc.doc_wimpy-denim-okapi
      github.com/seissol/seissol git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-crimson-buffalo.sh
        container: qc.doc_hilly-cinnabar-wildebeest
      github.com/seissol/seissol markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-aquamarine-jellyfish.sh
        container: qc.doc_boozy-cardinal-serval
      github.com/seissol/seissol restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-brown-bandicoot.sh
        container: qc.doc_chewy-myrtle-dodo
  QC.Lic:
    repos:
      github.com/seissol/seissol licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-puce-octopus.sh
        container: qc.lic_snappy-myrtle-snake
  QC.Met:
    repos:
      github.com/seissol/seissol cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-magenta-cuttlefish.sh
        container: qc.met_gamy-auburn-mandrill
  QC.Sec:
    repos:
      github.com/seissol/seissol bandit:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-cinnabar-lizard.sh
        container: qc.sec_randy-pumpkin-grasshopper
  QC.Sty:
    repos:
      github.com/seissol/seissol flake8:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-olive-millipede.sh
        container: qc.sty_cloudy-sepia-crocodile
      github.com/seissol/seissol jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-purple-starfish.sh
        container: qc.sty_goopy-linen-spoonbill
  QC.Ver:
    repos:
      github.com/seissol/seissol get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-persimmon-horse.sh
        container: qc.ver_fuzzy-linen-nightingale
timeout: 5400
