config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/SeisSol/SeisSol:
      branch: master
      repo: https://github.com/SeisSol/SeisSol
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/SeisSol/SeisSol git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-myrtle-gopher.sh
        container: qc.acc_smelly-bistre-lynx
  QC.Doc:
    repos:
      github.com/SeisSol/SeisSol find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-firebrick-hyrax.sh
        container: qc.doc_shaggy-aqua-discus
      github.com/SeisSol/SeisSol git:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-green-malamute.sh
        container: qc.doc_surly-smalt-zebra
      github.com/SeisSol/SeisSol markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-celadon-flounder.sh
        container: qc.doc_flabby-rust-meerkat
      github.com/SeisSol/SeisSol restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-amethyst-hyrax.sh
        container: qc.doc_clammy-white-dachshund
  QC.Lic:
    repos:
      github.com/SeisSol/SeisSol licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-chocolate-crane.sh
        container: qc.lic_cozy-smalt-wrasse
  QC.Sec:
    repos:
      github.com/SeisSol/SeisSol bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-corn-mayfly.sh
        container: qc.sec_pretty-mustard-tamarin
  QC.Sty:
    repos:
      github.com/SeisSol/SeisSol flake8:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-salmon-horse.sh
        container: qc.sty_snoopy-tan-sparrow
      github.com/SeisSol/SeisSol jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-viridian-albatross.sh
        container: qc.sty_muzzy-tan-akbash
  QC.Ver:
    repos:
      github.com/SeisSol/SeisSol get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-fuchsia-kangaroo.sh
        container: qc.ver_scummy-crimson-wrasse
timeout: 5400
