config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/SeisSol/SeisSol:
      branch: master
      repo: https://github.com/SeisSol/SeisSol
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/SeisSol/SeisSol git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-olive-frog.sh
        container: qc.acc_craggy-russet-affenpinscher
  QC.Doc:
    repos:
      github.com/SeisSol/SeisSol find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-brown-grouse.sh
        container: qc.doc_sickly-mauve-collie
      github.com/SeisSol/SeisSol git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-coral-akita.sh
        container: qc.doc_zippy-denim-oyster
      github.com/SeisSol/SeisSol markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-tan-gorilla.sh
        container: qc.doc_skanky-burgundy-uguisu
      github.com/SeisSol/SeisSol restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-myrtle-discus.sh
        container: qc.doc_flabby-pear-moose
  QC.Lic:
    repos:
      github.com/SeisSol/SeisSol licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-copper-giraffe.sh
        container: qc.lic_cheeky-platinum-dog
  QC.Met:
    repos:
      github.com/SeisSol/SeisSol cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-champagne-woodpecker.sh
        container: qc.met_boozy-red-dingo
  QC.Sec:
    repos:
      github.com/SeisSol/SeisSol bandit:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-rust-hedgehog.sh
        container: qc.sec_tasty-eggplant-raccoon
  QC.Sty:
    repos:
      github.com/SeisSol/SeisSol flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-thistle-coati.sh
        container: qc.sty_snappy-salmon-mongoose
      github.com/SeisSol/SeisSol hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-dandelion-ladybird.sh
        container: qc.sty_gimpy-khaki-frog
      github.com/SeisSol/SeisSol jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-charcoal-wrasse.sh
        container: qc.sty_skimpy-saffron-chimpanzee
      github.com/SeisSol/SeisSol oclint:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-khaki-grouse.sh
        container: qc.sty_baggy-buff-tapir
  QC.Uni:
    repos:
      github.com/SeisSol/SeisSol pytest:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-peach-hyrax.sh
        container: qc.uni_gloppy-chartreuse-cat
  QC.Ver:
    repos:
      github.com/SeisSol/SeisSol get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-magenta-goat.sh
        container: qc.ver_clammy-olivine-albatross
timeout: 5400
