config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/SeisSol/SeisSol:
      branch: cff
      repo: https://github.com/SeisSol/SeisSol
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/SeisSol/SeisSol git:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-jade-bat.sh
        container: qc.acc_surly-peach-angora
  QC.Doc:
    repos:
      github.com/SeisSol/SeisSol find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-firebrick-greyhound.sh
        container: qc.doc_cozy-amber-swan
      github.com/SeisSol/SeisSol git:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-pink-slug.sh
        container: qc.doc_snippy-violet-catfish
      github.com/SeisSol/SeisSol markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-red-manatee.sh
        container: qc.doc_skinny-sapphire-saola
      github.com/SeisSol/SeisSol restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-russet-termite.sh
        container: qc.doc_gloppy-harlequin-wombat
  QC.Lic:
    repos:
      github.com/SeisSol/SeisSol licensee:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-beige-bonobo.sh
        container: qc.lic_frumpy-vermilion-akbash
  QC.Met:
    repos:
      github.com/SeisSol/SeisSol cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-malachite-husky.sh
        container: qc.met_gloppy-vermilion-lemming
  QC.Sec:
    repos:
      github.com/SeisSol/SeisSol bandit:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-jade-caterpillar.sh
        container: qc.sec_ready-yellow-axolotl
  QC.Sty:
    repos:
      github.com/SeisSol/SeisSol flake8:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-firebrick-cockroach.sh
        container: qc.sty_sloppy-cerulean-affenpinscher
      github.com/SeisSol/SeisSol jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-emerald-fox.sh
        container: qc.sty_wimpy-cerulean-camel
  QC.Ver:
    repos:
      github.com/SeisSol/SeisSol get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-xanthic-sheepdog.sh
        container: qc.ver_baggy-peach-bird
timeout: 5400
