config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/seissol/seissol:
      branch: master
      repo: https://github.com/seissol/seissol
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/seissol/seissol git:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-alizarin-scorpion.sh
        container: qc.acc_paltry-pink-spider
  QC.Doc:
    repos:
      github.com/seissol/seissol find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-olivine-slug.sh
        container: qc.doc_silly-violet-mouse
      github.com/seissol/seissol git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-emerald-retriever.sh
        container: qc.doc_hasty-crimson-abyssinian
      github.com/seissol/seissol markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-sapphire-gharial.sh
        container: qc.doc_homey-puce-rattlesnake
      github.com/seissol/seissol restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-salmon-coyote.sh
        container: qc.doc_cloudy-seashell-hummingbird
  QC.Lic:
    repos:
      github.com/seissol/seissol licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-lime-bat.sh
        container: qc.lic_lousy-bistre-gharial
  QC.Met:
    repos:
      github.com/seissol/seissol cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-tangerine-ocelot.sh
        container: qc.met_gimpy-saffron-falcon
  QC.Sec:
    repos:
      github.com/seissol/seissol bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-coral-oriole.sh
        container: qc.sec_snoopy-tomato-barnacle
  QC.Sty:
    repos:
      github.com/seissol/seissol flake8:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-gold-balinese.sh
        container: qc.sty_stinky-xanthic-dog
      github.com/seissol/seissol hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-chocolate-penguin.sh
        container: qc.sty_hazy-amethyst-coral
      github.com/seissol/seissol jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-heliotrope-hippopotamus.sh
        container: qc.sty_slimy-magenta-anteater
      github.com/seissol/seissol oclint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-salmon-dachsbracke.sh
        container: qc.sty_scummy-lilac-serval
  QC.Uni:
    repos:
      github.com/seissol/seissol pytest:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-puce-avocet.sh
        container: qc.uni_gamy-linen-centipede
  QC.Ver:
    repos:
      github.com/seissol/seissol get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-firebrick-bloodhound.sh
        container: qc.ver_sickly-cinnabar-donkey
timeout: 5400
